# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.2"
manifest_format = "2.0"
project_hash = "3250d2d7d1346ac6bb1bc0c9097ccc86669f45b7"

[[deps.BinaryFields]]
deps = ["Random", "SIMD"]
git-tree-sha1 = "a7b2bd18128150a557f9016173f9006820965ff3"
repo-rev = "main"
repo-subdir = "BinaryFields"
repo-url = "https://github.com/bcc-research/CryptoUtilities.jl"
uuid = "0fee9d7f-8397-4f0d-9ec6-117db1666467"
version = "0.1.0"

[[deps.BinaryReedSolomon]]
deps = ["BinaryFields"]
git-tree-sha1 = "b2469407342ac70a76e001b0b7c0c3b00d81ddf9"
repo-rev = "main"
repo-subdir = "BinaryReedSolomon"
repo-url = "https://github.com/bcc-research/CryptoUtilities.jl.git"
uuid = "8a283c49-c6d0-46c5-bbc1-5b2a51f34960"
version = "0.1.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.MerkleTree]]
deps = ["SHA"]
git-tree-sha1 = "12adbda009f2fa53b79ae4d42b4c712d2cb7c8e1"
repo-rev = "main"
repo-subdir = "MerkleTree"
repo-url = "https://github.com/bcc-research/CryptoUtilities.jl.git"
uuid = "225b011c-e439-4471-b39b-04a9a0fe32f0"
version = "0.1.0"

[[deps.PrecompileTools]]
deps = ["Preferences"]
git-tree-sha1 = "5aa36f7049a63a1528fe8f7c3f2113413ffd4e1f"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
version = "1.2.1"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "9306f6085165d270f7e3db02af26a400d580f5c6"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.4.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.SIMD]]
deps = ["PrecompileTools"]
git-tree-sha1 = "fea870727142270bdf7624ad675901a1ee3b4c87"
uuid = "fdea26ae-647d-5447-a871-4b548cad5224"
version = "3.7.1"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
